version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - resumate-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - resumate-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=resumate

networks:
  resumate-network:
    driver: bridge

volumes:
  mongodb_data: